import Head from "next/head";
import React from "react";
import Header from "../components/Header";

import styles from "../styles/about.module.css";

const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aobut Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="#">About Page</a>
        </h1>
 

        <p className={styles.description}>
          Lorem ipsum dolor sit amen consenter adipisicing elit. Enim
          similitude commode minima porno, option quae magni aliquid iste illo?
          Esse dignissimos tempore adipisci ipsum ipsa architecto commodi, sequi
          ipsam accusamus est officia quae, incidunt sunt sit! Dolores,
          quibusdam praesentium. Velit nesciunt ut natus voluptatem architecto
          veritatis iste, iusto ea blanditiis. Perspiciatis, mollitia molestias
          quia optio facilis aliquid laboriosam nihil praesentium, ullam velit
        
        </p>

         
      </main>
    </div>
  );
};

export default About;
